language: node_js
node_js:
  - "5.1"
  - "5.0"
  - "4.1"
  - "4.0"

addons:
  sauce_connect: true
  # Node 5 requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8 # This is linked to the issue above with Node 5

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install --loglevel silent
  - $(npm bin)/typings install

before_script: rm -rf dist

script:
  - $(npm bin)/tsc
  - npm test